### PR TITLE
Use router provider for error handling #459

### LINKED ISSUE #459: Investigate using router provider for some error handling
https://reactrouter.com/en/main/start/tutorial#handling-not-found-errors allows us to have 404 pages for invalid ids, and more general error pages for 500 we could look at implementing. Could conflict with the style of SciGateway 404 pages.

### PR DESCRIPTION
**Pull request by MatteoGuarnaccia5**
## Description

see #459

## Testing instructions

Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage
- [ ] {more steps here}

## Agile board tracking

closes #459

### CODE REVIEW

**Comment by MatteoGuarnaccia5** [comment]
The basic error page I created works on scigateway as well, aside from 404 errors. They use the inbuilt scigateway page

**Comment by joshuadkitenge** [comment]
I can't seem to trigger this error. How did you trigger the page ??

**Comment by joshuadkitenge** [comment]
Also this issues is to Investigate use react router for invalid IDs for GET requests, such as invalid landing page URLs. The focus was specifically on these scenario, not on general usage.

**Comment by MatteoGuarnaccia5** [comment]
> Also this issues is to Investigate use react router for invalid IDs for GET requests, such as invalid landing page URLs. The focus was specifically on these scenario, not on general usage.

Ah okay, in that case than it has no use, as scigateways 404 error page supersedes it

**Comment by joshuadkitenge** [comment]
Investigate this further please. the case i suggested doesn't use the 404 page

**Comment by joshuadkitenge** [comment]
#459

**Pull request closed without merging**
