### PR TITLE
allow the user to select None when a allowed list of values is used #391

### LINKED ISSUE #391: allow the user to select None when a allowed list of values is used

### PR DESCRIPTION
**Pull request by joshuadkitenge**
## Description

allow the user to select None when a allowed list of values is used

## Testing instructions

Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage
- [ ] {more steps here}

## Agile board tracking

closes #391

### CODE REVIEW

**Review by joelvdavies — CHANGES_REQUESTED** [review]
I think none should only be an option if the field is not mandatory.

**Comment by joshuadkitenge** [comment]
> I think none should only be an option if the field is not mandatory.

We have error handling for that case. It makes sense that the drop down to be consistent

**Review by MatteoGuarnaccia5 — APPROVED** [review]
LGTM

**Comment by joelvdavies** [comment]
> > I think none should only be an option if the field is not mandatory.
> 
> We have error handling for that case. It makes sense that the drop down to be consistent.
> 
> also the default value should always also be in the dropdown (default value : '' (add))

The value should need to be there e.g. https://mui.com/material-ui/react-select/ provided it has the right type. But I see what you mean.

**Review by joelvdavies — APPROVED** [review]

**Pull request merged**
