### PR TITLE
configuration for release notes generation

### LINKED ISSUE #806: Disable dependencies from appearing in changelogs?
See first file on https://github.com/ral-facilities/scigateway/pull/1405/files. I think this would affect the generate changelog button on the releases section.

### PR DESCRIPTION
**Pull request by MatteoGuarnaccia5**
## Description

Added configuration for custom auto generated release notes.
Made relevant changes in documentation.

The same changes would need to be made in ims-api

## Testing instructions

Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage
- [ ] {more steps here}

## Agile board tracking

closes #806

### CODE REVIEW

**Comment by MatteoGuarnaccia5** [comment]
image

An example of what the changelog now looks like with the new config

**Review by joshuadkitenge — CHANGES_REQUESTED** [review]
https://keepachangelog.com/en/1.0.0/

**Comment by MatteoGuarnaccia5** [comment]
The rules for the config mean that we need to add some more labels to github, and assign PRs with the correct labels.

**Comment by MatteoGuarnaccia5** [comment]
This PR is an example for custom changelogs, which are categorized based off the the labels on pull requests. An example file has been included to show a workflow that automatically labels pull requests based off of their branch name. This change would mean making changes to the wiki, the pull request template, and optionally the readMe.

The labels used in this PR are examples, you can pick whatever labels / rules to use for future. But should be included in any documentation created.

**Pull request closed without merging**
