### PR TITLE
fix duplicate name error for copyTo #553

### LINKED ISSUE #553: fix duplicate names (all dialogs)
Check if a you can change the name (duplicate value) to the same name with capital letter 
- All dialog work correct with mock data requires backend change to work 
    - works 

Check move to and copy to

- Fix the systems copy to and the systems copy to
    - they need to use code instead of name

### PR DESCRIPTION
**Pull request by joshuadkitenge**
## Description

fix the copy to and move to for the directory dialogs. Use the code for the duplicate check instead of name.  

## Testing instructions

Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage
- [ ] {more steps here}

## Agile board tracking

closes #553

### CODE REVIEW

**Review by MatteoGuarnaccia5 — DISMISSED** [review]
LGTM

**Review by joelvdavies — CHANGES_REQUESTED** [review]
I only just realised we seem to have missed out tests on duplicates. I think it would be good if they could be added here.

**Comment by joelvdavies** [comment]
Is it possible to check the moves as well with the same tests you added? We are missing those too.

**Comment by joshuadkitenge** [comment]
> Is it possible to check the moves as well with the same tests you added? We are missing those too.

The move doesn't have the duplicate same logic . The failed response ( for duplicate) is tested in the hook itself catalogueCategories.test.tsx

**Review by MatteoGuarnaccia5 — APPROVED** [review]
LGTM

**Review by joelvdavies — APPROVED** [review]

**Pull request merged**
