### PR TITLE
Add Delete Image 

### LINKED ISSUE #1074: Delete images
#### Tasks:
- [ ] Create a **Delete** confirmation dialog for images.
- [ ] Implement a **DELETE** endpoint to remove images from the backend.
- [ ] Add a **Delete** `MenuItem` to the **Images** for each image tileActionMenu.

#### Notes:
- No bulk delete this should be later with #183
- This could be shared with #1069

### PR DESCRIPTION
**Pull request by asuresh-code**
## Description

#1074 

## Testing instructions

**Checkout `**add-delete-endpoint-for-image-#38**` on the Object Storage API repo to test with the api.**

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage
- [ ] {more steps here}

## Agile board tracking

closes #1074

### CODE REVIEW

**Review by joshuadkitenge — CHANGES_REQUESTED** [review]
https://github.com/user-attachments/assets/33a59f7f-1f4c-4037-93d1-7e57a95c16ab

**Comment by asuresh-code** [comment]
> delete.error.mp4

I'm not sure if the error I recreated and addressed was exactly what you found; I believe the issue is that when you delete an image in the lightbox, it tries to GET the image, only to get this error since it does not exist anymore. I've fixed it by simply closing the lightbox if you delete an image.

**Review by joshuadkitenge — APPROVED** [review]
LGTM

**Review by rowan04 — COMMENTED** [review]
looks good, just 2 minor comments

**Review by joshuadkitenge — APPROVED** [review]

**Review by rowan04 — APPROVED** [review]
lgtm 🎉

**Pull request merged**
