### PR TITLE
Print button on landing pages #164

### LINKED ISSUE #164: Print button on the landing page
Add Print button on the catalogue item landing page and manufacturer landing page.
wait for #144 so you can modify the manufacturer landing page

### PR DESCRIPTION
**Pull request by joshuadkitenge**
## Description
Add print button on landing page. 
Cypress cannot interact with the browser print dialog. No e2e tests

wait for #144 to add the print button on the manufacturer landing page.
 

## Testing instructions

Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage
- [ ] open browser print dialog 
- [ ] {more steps here}

## Agile board tracking
closes #164

### CODE REVIEW

**Review by MatteoGuarnaccia5 — COMMENTED** [review]
image

I don't know how easy/difficult this would be, but as a user if I wanted to print the page. I wouldn't want this on the page I print out. I'd want the very top of the page to be 'Camera 1' for example

**Comment by MatteoGuarnaccia5** [comment]
Also the manufacturer landing page link isn't there anymore, on the manufacturer table or catalogue item table, the name is just greyed out for me now

**Comment by joshuadkitenge** [comment]
> image
> 
> I don't know how easy/difficult this would be, but as a user if I wanted to print the page. I wouldn't want this on the page I print out. I'd want the very top of the page to be 'Camera 1' for example



> image
> 
> I don't know how easy/difficult this would be, but as a user if I wanted to print the page. I wouldn't want this on the page I print out. I'd want the very top of the page to be 'Camera 1' for example


This issue was discussed in the user feedback demo and it was decided to do it this way for now. If users/stakeholders have any issues with it we would change it but that would be a non-mvp task.

**Comment by joshuadkitenge** [comment]
> Also the manufacturer landing page link isn't there anymore, on the manufacturer table or catalogue item table, the name is just greyed out for me now

I haven't touched those files in this pr so it is probably a problem on your side

**Comment by joshuadkitenge** [comment]
> > image
> > I don't know how easy/difficult this would be, but as a user if I wanted to print the page. I wouldn't want this on the page I print out. I'd want the very top of the page to be 'Camera 1' for example
> 
> > image
> > I don't know how easy/difficult this would be, but as a user if I wanted to print the page. I wouldn't want this on the page I print out. I'd want the very top of the page to be 'Camera 1' for example
> 
> This issue was discussed in the user feedback demo and it was decided to do it this way for now. If users/stakeholders have any issues with it we would change it but that would be a non-mvp task.

I've managed to remove the buttons from the print. The tabs don't exist in the production version of the website so that can be ignored

**Review by MatteoGuarnaccia5 — APPROVED** [review]
Works well for me

**Pull request merged**
